# Generated by Django 5.1.3 on 2024-12-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('tech', '기술 블로그'), ('free', '자유 게시판'), ('guest', '방명록')], default='free', max_length=10),
        ),
    ]
