# Generated by Django 5.1.3 on 2024-12-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, error_messages={'unique': '이미 사용 중인 이메일입니다.'}, max_length=254, unique=True),
        ),
    ]
